---
- name: Create Oracle Database
  hosts: all
  collections:
    - ibre5041.ansible_oracle_modules
  become: true
  any_errors_fatal: true

  pre_tasks:
    - name: Validate inputs
      ansible.builtin.assert:
        that:
          - oracle_environment is defined
          - oracle_environment in ['dev', 'staging', 'prod']
          - target_db is defined
        fail_msg: "Required: oracle_environment and target_db"

  roles:
    - role: catalog_loader
    - role: oracle_database
