---
- name: Data Guard Failover
  hosts: all
  collections:
    - ibre5041.ansible_oracle_modules
  become: true
  any_errors_fatal: true

  pre_tasks:
    - name: Validate inputs
      ansible.builtin.assert:
        that:
          - target_db is defined
          - failover_target is defined

  roles:
    - role: catalog_loader
    - role: oracle_dataguard
      vars:
        dg_operation: failover
