---
- name: Manage Oracle Directories
  hosts: all
  collections:
    - ibre5041.ansible_oracle_modules
  become: true
  any_errors_fatal: true

  roles:
    - role: catalog_loader
    - role: oracle_directory_management
