---
# ============================================================
# RAC Topology Defaults
# ============================================================

oracle_install_type: rac
oracle_dbconfig_type: RAC
